version: "2"
services:
    app:
      build: 
        context: .docker/node/
      command: bash -c "npm install && npm start"
      ports:
        - 4200:4200
      volumes:
        - ./:/usr/src/app:rw
        - ./node_modules/:/usr/src/app/node_modules/:rw
    